env:
  global:
    - CC_TEST_REPORTER_ID: ecb24ed0e4ed09f50a512e0b9490e0caa3e2409bb5f1220af8935514279293d9
language: swift
xcode_workspace: ios-base.xcworkspace
xcode_scheme: ios-base
osx_image: xcode10
cache:
  - bundler
  - cocoapods
before_install:
  - pod repo update
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - bundle install
  - pod install
script:
  - set -o pipefail
  - xcodebuild -workspace ios-base.xcworkspace -scheme ios-base -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test | xcpretty --test --color
  - bundle exec danger
after_script:
  - slather coverage -s --scheme ios-base ios-base.xcodeproj
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode
  - ./cc-test-reporter after-build --debug -t cobertura --exit-code $TRAVIS_TEST_RESULT
