os: osx
language: swift
xcode_workspace: ios-base.xcworkspace
xcode_scheme: ios-base
osx_image: xcode9
xcode_sdk: iphonesimulator11
cache: cocoapods
install: true
before_install:
- bundle install
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6 (10.2" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
before_script:
- pod repo update
- pod install
- chmod u+x ./scripts/acceptance-tests.sh
- bundle exec danger
script:
- travis_retry ./scripts/acceptance-tests.sh
