language: swift
xcode_workspace: ios-base.xcworkspace
xcode_scheme: ios-base
osx_image: xcode9.4
cache: 
  - bundler
  - cocoapods
before_install:
  - pod repo update
install:
  - bundle install 
  - pod install
script:
  - set -o pipefail
  - xcodebuild -workspace ios-base.xcworkspace -scheme ios-base -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test | xcpretty --test --color
  - bundle exec danger
