name: Test

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run:  pod install
    - name: Run tests
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane:  test_develop